Nuevas funciones
leonadovaona/demo pull request #1
Opened 2018-04-23 01:52 UTC by leonadovaona

2018-04-23 12:40 UTC, evictorero requested changes

2018-04-23 12:40 UTC, evictorero commented on src/main/java/personas/example/demo/PersonController.java
> +        Person p = personService.findPersonById(mapPersons.values(), id);
En el update estaría bueno validar que el id de la url coincida con el id dentro de Person del request body. No es necesario pisar el objeto person, podes mandarle el que te llega por request body, de esa forma si falta algún valor se seteará nulo.

2018-04-23 12:40 UTC, evictorero commented on src/main/java/personas/example/demo/PersonController.java
>      @RequestMapping(method = RequestMethod.DELETE)
Podrías modificar todos los RequestMapping por una forma más corta que existe hoy y es similar. Por ejemplo en este caso sería @DeleteMapping

2018-04-23 12:40 UTC, evictorero commented on src/main/java/personas/example/demo/PersonController.java
> +        mapPersons.clear();
Esto no debería ser necesario, que se encargue el servicio de borrar solamente.

2018-04-23 12:40 UTC, evictorero commented on src/main/java/personas/example/demo/DAO/PersonDAO.java
> +        p.set
No es una buena práctica comitear código que no compila.

2018-04-25 21:19 UTC, merged

2018-04-25 21:20 UTC, leonadovaona commented
Actualización por un mal commit de master